# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(844, 779)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(455, 660))
        self.scheduleLabel = QtWidgets.QLabel(Dialog)
        self.scheduleLabel.setGeometry(QtCore.QRect(510, 200, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.scheduleLabel.setFont(font)
        self.scheduleLabel.setObjectName("scheduleLabel")
        self.nrs048CheckBox = QtWidgets.QCheckBox(Dialog)
        self.nrs048CheckBox.setGeometry(QtCore.QRect(510, 400, 221, 20))
        self.nrs048CheckBox.setObjectName("nrs048CheckBox")
        self.typeLabel = QtWidgets.QLabel(Dialog)
        self.typeLabel.setGeometry(QtCore.QRect(510, 360, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.typeLabel.setFont(font)
        self.typeLabel.setObjectName("typeLabel")
        self.customReportLabel = QtWidgets.QLabel(Dialog)
        self.customReportLabel.setGeometry(QtCore.QRect(510, 450, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.customReportLabel.setFont(font)
        self.customReportLabel.setObjectName("customReportLabel")
        self.previewReportPushButton = QtWidgets.QPushButton(Dialog)
        self.previewReportPushButton.setGeometry(QtCore.QRect(510, 670, 221, 31))
        self.previewReportPushButton.setObjectName("previewReportPushButton")
        self.screenSizeLabel = QtWidgets.QLabel(Dialog)
        self.screenSizeLabel.setGeometry(QtCore.QRect(40, 730, 111, 16))
        self.screenSizeLabel.setObjectName("screenSizeLabel")
        self.connectionStatusLabel = QtWidgets.QLabel(Dialog)
        self.connectionStatusLabel.setGeometry(QtCore.QRect(160, 730, 271, 16))
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 240, 221, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dailyCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.dailyCheckBox.setObjectName("dailyCheckBox")
        self.verticalLayout.addWidget(self.dailyCheckBox)
        self.weeklyCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.weeklyCheckBox.setObjectName("weeklyCheckBox")
        self.verticalLayout.addWidget(self.weeklyCheckBox)
        self.monthlyCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.monthlyCheckBox.setObjectName("monthlyCheckBox")
        self.verticalLayout.addWidget(self.monthlyCheckBox)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 160, 921, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.meterListLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.meterListLabel.setFont(font)
        self.meterListLabel.setObjectName("meterListLabel")
        self.horizontalLayout.addWidget(self.meterListLabel)
        self.reportConfigLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.reportConfigLabel.setFont(font)
        self.reportConfigLabel.setObjectName("reportConfigLabel")
        self.horizontalLayout.addWidget(self.reportConfigLabel)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(510, 490, 221, 103))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vssiCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.vssiCheckBox.setObjectName("vssiCheckBox")
        self.verticalLayout_3.addWidget(self.vssiCheckBox)
        self.harmonicsCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.harmonicsCheckBox.setObjectName("harmonicsCheckBox")
        self.verticalLayout_3.addWidget(self.harmonicsCheckBox)
        self.ldpCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.ldpCheckBox.setObjectName("ldpCheckBox")
        self.verticalLayout_3.addWidget(self.ldpCheckBox)
        self.eventsCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.eventsCheckBox.setObjectName("eventsCheckBox")
        self.verticalLayout_3.addWidget(self.eventsCheckBox)
        self.reportConfigLabel_2 = QtWidgets.QLabel(Dialog)
        self.reportConfigLabel_2.setGeometry(QtCore.QRect(40, 20, 456, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.reportConfigLabel_2.setFont(font)
        self.reportConfigLabel_2.setObjectName("reportConfigLabel_2")
        self.hostNameLabel = QtWidgets.QLabel(Dialog)
        self.hostNameLabel.setGeometry(QtCore.QRect(40, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hostNameLabel.setFont(font)
        self.hostNameLabel.setObjectName("hostNameLabel")
        self.portNumberLabel = QtWidgets.QLabel(Dialog)
        self.portNumberLabel.setGeometry(QtCore.QRect(40, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.portNumberLabel.setFont(font)
        self.portNumberLabel.setObjectName("portNumberLabel")
        self.saveCommandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.saveCommandLinkButton.setGeometry(QtCore.QRect(730, 720, 91, 41))
        self.saveCommandLinkButton.setObjectName("saveCommandLinkButton")
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(190, 70, 191, 88))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hostNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.hostNameLineEdit.setText("")
        self.hostNameLineEdit.setObjectName("hostNameLineEdit")
        self.verticalLayout_4.addWidget(self.hostNameLineEdit)
        self.portNumberLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.portNumberLineEdit.setObjectName("portNumberLineEdit")
        self.verticalLayout_4.addWidget(self.portNumberLineEdit)
        self.testConnectionpushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.testConnectionpushButton.setObjectName("testConnectionpushButton")
        self.verticalLayout_4.addWidget(self.testConnectionpushButton)
        self.reportsFolderLineEdit = QtWidgets.QLineEdit(Dialog)
        self.reportsFolderLineEdit.setGeometry(QtCore.QRect(510, 630, 221, 22))
        self.reportsFolderLineEdit.setObjectName("reportsFolderLineEdit")
        self.reportsFolderLabel = QtWidgets.QLabel(Dialog)
        self.reportsFolderLabel.setGeometry(QtCore.QRect(510, 610, 151, 16))
        self.reportsFolderLabel.setObjectName("reportsFolderLabel")
        self.meterTableWidget = QtWidgets.QTableWidget(Dialog)
        self.meterTableWidget.setGeometry(QtCore.QRect(36, 191, 341, 461))
        self.meterTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.meterTableWidget.setObjectName("meterTableWidget")
        self.meterTableWidget.setColumnCount(0)
        self.meterTableWidget.setRowCount(0)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(36, 676, 341, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateListPushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.updateListPushButton.setObjectName("updateListPushButton")
        self.horizontalLayout_2.addWidget(self.updateListPushButton)
        self.saveSelectedMeterListPushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.saveSelectedMeterListPushButton.setObjectName("saveSelectedMeterListPushButton")
        self.horizontalLayout_2.addWidget(self.saveSelectedMeterListPushButton)
        self.fileDialogPushButton = QtWidgets.QPushButton(Dialog)
        self.fileDialogPushButton.setGeometry(QtCore.QRect(740, 630, 21, 22))
        self.fileDialogPushButton.setObjectName("fileDialogPushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SEL-735 PQ Reporting"))
        self.scheduleLabel.setText(_translate("Dialog", "Schedule"))
        self.nrs048CheckBox.setText(_translate("Dialog", "NRS048 Standard Report"))
        self.typeLabel.setText(_translate("Dialog", "Type"))
        self.customReportLabel.setText(_translate("Dialog", "Create A Custom Report:"))
        self.previewReportPushButton.setText(_translate("Dialog", "Preview Report"))
        self.screenSizeLabel.setText(_translate("Dialog", "Connection Status:"))
        self.connectionStatusLabel.setText(_translate("Dialog", "..."))
        self.dailyCheckBox.setText(_translate("Dialog", "Daily"))
        self.weeklyCheckBox.setText(_translate("Dialog", "Weekly"))
        self.monthlyCheckBox.setText(_translate("Dialog", "Monthly"))
        self.meterListLabel.setText(_translate("Dialog", "Meter List"))
        self.reportConfigLabel.setText(_translate("Dialog", "Report Configuration"))
        self.vssiCheckBox.setText(_translate("Dialog", "Voltage Sag, Swell, Interruptions"))
        self.harmonicsCheckBox.setText(_translate("Dialog", "Harmonics (3,5,7)"))
        self.ldpCheckBox.setText(_translate("Dialog", "Load Profile Data"))
        self.eventsCheckBox.setText(_translate("Dialog", "PQ Events"))
        self.reportConfigLabel_2.setText(_translate("Dialog", "TEAM Software Host Details"))
        self.hostNameLabel.setText(_translate("Dialog", "Host Name:"))
        self.portNumberLabel.setText(_translate("Dialog", "API Port Number:"))
        self.saveCommandLinkButton.setText(_translate("Dialog", "Save"))
        self.hostNameLineEdit.setPlaceholderText(_translate("Dialog", "localhost"))
        self.portNumberLineEdit.setPlaceholderText(_translate("Dialog", "5630"))
        self.testConnectionpushButton.setText(_translate("Dialog", "Test Connection"))
        self.reportsFolderLabel.setText(_translate("Dialog", "Reports Folder Path"))
        self.updateListPushButton.setText(_translate("Dialog", "Update List"))
        self.saveSelectedMeterListPushButton.setText(_translate("Dialog", "Save Selection"))
        self.fileDialogPushButton.setText(_translate("Dialog", "..."))

